name: ğŸ”— GHA
on: [push, pull_request]

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-runner
  cancel-in-progress: true

jobs:
  # First stage: Only static checks, fast and prevent expensive builds from running.

  # static-checks:
  #   if: ${{ vars.DISABLE_GODOT_CI == '' }}
  #   name: ğŸ“Š Static checks
  #   uses: ./.github/workflows/static_checks.yml

  # Second stage: Run all the builds and some of the tests.

  android-build:
    if: ${{ vars.DISABLE_GODOT_CI == '' }}
    name: ğŸ¤– Android
    #needs: static-checks
    uses: ./.github/workflows/android_builds.yml

  ios-build:
    if: ${{ vars.DISABLE_GODOT_CI == '' }}
    name: ğŸ iOS
    #needs: static-checks
    uses: ./.github/workflows/ios_builds.yml

  # linux-build:
  #   if: ${{ vars.DISABLE_GODOT_CI == '' }}
  #   name: ğŸ§ Linux
  #   needs: static-checks
  #   uses: ./.github/workflows/linux_builds.yml

  # macos-build:
  #   if: ${{ vars.DISABLE_GODOT_CI == '' }}
  #   name: ğŸ macOS
  #   needs: static-checks
  #   uses: ./.github/workflows/macos_builds.yml

  # windows-build:
  #   if: ${{ vars.DISABLE_GODOT_CI == '' }}
  #   name: ğŸ Windows
  #   needs: static-checks
  #   uses: ./.github/workflows/windows_builds.yml

